defaults:
  # Common setup.
  - setup
  # This file.
  - _self_
  # - optional override:


device: cuda
dataset:
  name: digit_multiplication
  cot: False
  max_size: -1
  max_seq_len: 256

digit: 4
train_path: ${data_dir}/${digit}_by_${digit}_mult/train.txt
val_path: ${data_dir}/${digit}_by_${digit}_mult/valid.txt

batch_size: 256
epochs: 20
learning_rate: 3e-4


model:
  arch: deq
  d_model: 64
  n_layers: 2
  n_heads: 2
  d_ff: 256 # 64 * 4
  dropout: 0.1
  # Number of tokens to predict in one iteration of fixed-point
  chunk_size: 12
  # Number of iterations of fixed-point
  max_chunk: 12

save_model: False
device_suggested: ${device}
is_this_overridden: no
